version: "2.0"

vms:

  ##############################################################
  # 1. Standard x86_64 PC — boots from ISO first
  ##############################################################
  mypc:
    arch: x86_64
    machine: q35
    accel: kvm
    cpus: 4
    cpu_model: host
    cpu_max_speed: 75  # Limit CPU to 75% of max speed
    memory: 4096

    boot:
      - cdrom
      - disk

    networks:
      - type: user
        forwards:
          - host_port: 2222
            guest_port: 22        # SSH access
          - host_port: 8081
            guest_port: 80        # Web server example

    disks:
      - path: disks/mypc.qcow2
        format: qcow2
        interface: virtio
        size: 20G                 # auto-create if missing

    cdrom:
      path: iso/alpine.iso        # bootable ISO
      interface: ide

    hardware:
      vendor: "QEMU-PC"
      product: "MyPC"
      serial_number: AUTO
      board_id: "BOARD-MYPC"
      bios: OVMF
      display:
        type: spice
        width: 1920
        height: 1080
        dpi: 96
      battery:
        present: false
      sensors:
        temperature: true
        fan: true

    audio:
      type: ac97

    usb:
      - device: usb-tablet
      - device: usb-kbd

    args:
      - "-vga qxl"
      - "-device ich9-usb-ehci1"
      - "-device ich9-usb-uhci1"

  ##############################################################
  # 2. High-performance PC with VNC display
  ##############################################################
  pc2:
    arch: x86_64
    machine: q35
    cpus: 8
    memory: 16384
    networks:
      - type: user
        forwards:
          - host_port: 2223
            guest_port: 22

    disks:
      - path: disks/pc2.qcow2
        format: qcow2
        interface: virtio
        size: 30G

    hardware:
      vendor: "QEMU"
      product: "Performance-PC"
      serial_number: AUTO
      display:
        type: vnc
        port: 5905
      sensors: {}
      battery: {}

    args:
      - "-enable-kvm"
      - "-vga virtio"

  ##############################################################
  # 3. ARM Mobile Device Emulation (phone-like)
  ##############################################################
  mobile1:
    arch: aarch64
    machine: virt
    cpus: 4
    memory: 2048
    accel: tcg        # no KVM on ARM emulation
    boot:
      - disk

    networks:
      - type: user
        forwards:
          - host_port: 2224
            guest_port: 22

    disks:
      - path: disks/mobileos.qcow2
        format: qcow2
        interface: virtio
        size: 8G

    hardware:
      vendor: "MobileVendor"
      product: "MobilePhone1"
      serial_number: AUTO
      imei: AUTO
      board_id: "MOBILE-001"
      display:
        type: virtio-gpu
        width: 1080
        height: 2340
      battery:
        present: true
        capacity_mAh: 4000
      sensors:
        accelerometer: true
        gyroscope: true
        proximity: true
        temperature: true

    usb:
      - device: usb-net
      - device: usb-keyboard

    args:
      - "-device virtio-gpu-pci"
      - "-device virtio-mouse-device"
      - "-device virtio-keyboard-device"
      - "-nographic"       # run without GUI (optional)

  ##############################################################
  # 4. GPU Passthrough Example (placeholder)
  ##############################################################
  gpuvm:
    arch: x86_64
    machine: q35
    cpus: 6
    memory: 8192
    accel: kvm
    disks:
      - path: disks/gpuvm.qcow2
        format: qcow2
        interface: virtio
        size: 40G

    hardware:
      vendor: "QEMU"
      product: "GPU-VM"
      serial_number: AUTO
      display:
        type: none

    gpu_passthrough:
      pci_id: "0000:01:00.0"
      audio_id: "0000:01:00.1"

    args:
      - "-enable-kvm"
      - "-cpu host"
      - "-device vfio-pci,host=0000:01:00.0,multifunction=on"
      - "-device vfio-pci,host=0000:01:00.1"

  ##############################################################
  # 5. Low-Power Embedded Device (ESP32-like)
  ##############################################################
  esp32_sim:
    arch: x86_64
    machine: q35
    cpus: 1
    cpu_max_speed: 25  # Limit to 25% - simulates low-power MCU
    memory: 512

    networks:
      - type: user
        forwards:
          - host_port: 2225
            guest_port: 22

    disks:
      - path: disks/esp32sim.qcow2
        format: qcow2
        interface: virtio
        size: 2G

    hardware:
      vendor: "Espressif"
      product: "ESP32-Simulator"
      serial_number: AUTO

    args:
      - "-nographic"

  ##############################################################
  # 6. Socket Networking - VM-to-VM Communication (Server)
  ##############################################################
  net_server:
    arch: x86_64
    machine: q35
    cpus: 2
    memory: 1024

    networks:
      - type: socket
        mode: server
        path: /tmp/qemu-lan.sock
        mac: "52:54:00:12:34:01"

    disks:
      - path: disks/server.qcow2
        format: qcow2
        interface: virtio
        size: 10G

    hardware:
      vendor: "QEMU"
      product: "Network-Server"

  ##############################################################
  # 7. Socket Networking - VM-to-VM Communication (Client)
  ##############################################################
  net_client:
    arch: x86_64
    machine: q35
    cpus: 2
    memory: 1024

    networks:
      - type: socket
        mode: client
        path: /tmp/qemu-lan.sock
        mac: "52:54:00:12:34:02"
        conditions:
          latency: 50ms
          packet_loss: 2
          bandwidth: 100mbps

    disks:
      - path: disks/client.qcow2
        format: qcow2
        interface: virtio
        size: 10G

    hardware:
      vendor: "QEMU"
      product: "Network-Client"

  ##############################################################
  # 8. Multicast Network - Multiple VMs on Same Network
  ##############################################################
  mcast_vm1:
    arch: x86_64
    machine: q35
    cpus: 1
    memory: 512

    networks:
      - type: multicast
        address: "230.0.0.1:1234"
        mac: "52:54:00:aa:bb:01"

    disks:
      - path: disks/mcast1.qcow2
        format: qcow2
        interface: virtio
        size: 5G

  ##############################################################
  # 9. TAP Network with Bridge (requires host bridge setup)
  ##############################################################
  tap_vm:
    arch: x86_64
    machine: q35
    cpus: 2
    memory: 2048

    networks:
      - type: tap
        ifname: tap0
        bridge: br0
        mac: "52:54:00:ab:cd:ef"

    disks:
      - path: disks/tapvm.qcow2
        format: qcow2
        interface: virtio
        size: 20G

  ##############################################################
  # 10. WAN Simulation - High Latency & Packet Loss
  ##############################################################
  wan_sim:
    arch: x86_64
    machine: q35
    cpus: 2
    memory: 1024

    networks:
      - type: socket
        mode: server
        path: /tmp/qemu-wan.sock
        conditions:
          latency: 200ms
          packet_loss: 10
          bandwidth: 5mbps
          jitter: 50ms

    disks:
      - path: disks/wan.qcow2
        format: qcow2
        interface: virtio
        size: 10G

